### ISSUE TITLE
game refuses to fully load / startup

### ISSUE THREAD

**Issue by VoidSpawned** [Moffein/Risky_Artifacts#11]
while just using this mod I get this error

mod version: 1.4.10

[Error: Unity Log] ArgumentNullException: Value cannot be null.
Parameter name: key
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].FindEntry (TKey key) (at <44afb4564e9347cf99a1865351ea8f4a>:IL_0008)
System.Collections.Generic.Dictionary`2[TKey,TValue].ContainsKey (TKey key) (at <44afb4564e9347cf99a1865351ea8f4a>:IL_0000)
R2API.LanguageAPI.Language_TokenIsRegistered (On.RoR2.Language+orig_TokenIsRegistered orig, RoR2.Language self, System.String token) (at <ec926c74969941989bfd154cae03a0fa>:IL_0095)
DMD<>?-365849088.Hook<RoR2.Language::TokenIsRegistered>?1001264128 (RoR2.Language , System.String ) (at <13a5e23bf2024cbe9c9bee09108db849>:IL_000A)
RoR2.UI.LogBook.LogBookController.IsEntryPickupItemWithoutLore (RoR2.UI.LogBook.Entry& entry) (at <7a5120bd69d843a8b8e90b8cce404663>:IL_0021)
RoR2.UI.LogBook.Entry.get_isWip () (at <7a5120bd69d843a8b8e90b8cce404663>:IL_0006)
RoR2.UI.LogBook.LogBookController.RegisterViewables (RoR2.UI.LogBook.CategoryDef[] categoriesToGenerateFrom) (at <7a5120bd69d843a8b8e90b8cce404663>:IL_0078)
RoR2.UI.LogBook.LogBookController.BuildStaticData () (at <7a5120bd69d843a8b8e90b8cce404663>:IL_000A)
RoR2.UI.LogBook.LogBookController.OnUserSignIn (RoR2.LocalUser obj) (at <7a5120bd69d843a8b8e90b8cce404663>:IL_0000)
RoR2.LocalUserManager.AddUser (Rewired.Player inputPlayer, RoR2.UserProfile userProfile) (at <7a5120bd69d843a8b8e90b8cce404663>:IL_004E)
RoR2.LocalUserManager.AddMainUser (RoR2.UserProfile userProfile) (at <7a5120bd69d843a8b8e90b8cce404663>:IL_0005)
RoR2.LocalUserManager.AddMainUser (System.String userProfileName) (at <7a5120bd69d843a8b8e90b8cce404663>:IL_0017)
RoR2.LocalUserManager+<>c.<Init>g__LogInWithPreviousSessionUser|24_0 () (at <7a5120bd69d843a8b8e90b8cce404663>:IL_000C)
RoR2.SaveSystem.LoadUserProfiles () (at <7a5120bd69d843a8b8e90b8cce404663>:IL_00E3)
RoR2.RoR2Application+<InitializeGameRoutine>d__69.MoveNext () (at <7a5120bd69d843a8b8e90b8cce404663>:IL_0271)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <469e86e97fa2467ebffe49bbd6086325>:IL_0026)

**Comment by Moffein** [comment]
This is a vanilla error related to modded achievements that was added in the latest game update.
