### ISSUE TITLE
Question: Is it possible to add new bossses from MODs that introduces boss enemy to the pool of Artifact of Origination?

### ISSUE THREAD

**Issue by KaitoXion** [Moffein/Risky_Artifacts#17]
An Inquiry;
Wonder if its possible to add new Bosses from Mods that introduce Boss Enemy to the Pool of Artifact of Origination?
E.g Brass Monolite, SteelMechorilla, Regigigas, etc.

Like for example, via Config.cfg? Honestly I do not think that this is possible Since the game was never created with this in mind.
This is a humble inquiry from someone that did not know the back-end side of the game.

Please do pardon me if it appears to be too annoying. Is cool to ignore this post shall it be too much in a way.

**Comment by Moffein** [comment]
It's possible, but they needed to be added from the other mod's end.
Ancient Wisp and Regigigas have Origination support, while Monolith and Mechorilla don't. If you'd like them to support the artifact, try contacting the devs of those mods.

**Comment by KaitoXion** [comment]
Monolith appears to belongs to Forgotten Relics Mod.

Thank you very much for your advice. I'll do so as suggested. Really appreciate your clear insight,
