### ISSUE TITLE
Add config options for basic on/off

### ISSUE THREAD

**Issue by EmuLegs** [Moffein/Risky_Artifacts#2]
I would love to play with this mod, but it forces all the Artifacts to be listed, can you please add some config options to enable/disable each one 

I personally would like to turn off 
Artifact of Expansion (have a mod that makes this one pointless)
and Artifact of Conformity

**Comment by EmuLegs** [comment]
also, wona make Artifact of Warfare give +50% gold aswell :p

**Comment by Moffein** [comment]
Added Enable/Disable config options for all artifacts.
Probably won't give Warfare any bonuses since it's meant to be a pure challenge artifact.

**Comment by EmuLegs** [comment]
thankyou :)
