### ISSUE TITLE
Umbral Mithrix Compatability Issue

### ISSUE THREAD

**Issue by StrangeofMishahu** [Moffein/Risky_Artifacts#20]
Artifact of the phantom is affected by Umbral Mithrix. He does not take status affects, and takes increased damage from things like shurikens, fireworks, orbital strikes, and more weird, stupid stuff.

**Comment by Moffein** [comment]
What's happening is probably that Umbral Mithrix is directly modifying Mithrix himself, so whenever he shows up anywhere else (Phantom, Simulacrum events, etc.), he'll have those modifications applied.
