### ISSUE TITLE
Question : artifact of hunted, how to add huntress survival into the spawn list?

### ISSUE THREAD

**Issue by KaitoXion** [Moffein/Risky_Artifacts#22]
How to add huntress survival into the spawn list?

> ## List of bodies to be added. Format is BodyName separated by comma. To specify custom stats, do BodyName:Cost:HPMult(float):DamageMult(float)
>  # Setting type: String
>  # Default value: CommandoBody, Bandit2Body, ToolbotBody, MercBody, MageBody, LoaderBody, CrocoBody, RailgunnerBody, RocketSurvivorBody, CHEF, SniperClassicBody, MinerBody, HANDOverclockedBody, RobPaladinBody, SS2UChirrBody, SS2UCyborgBody, SS2UExecutionerBody, SS2UPyroBody, SS2UNemmandoBody, RobDriverBody, DeputyBody
>  Spawnlist = CommandoBody, Bandit2Body, ToolbotBody, MercBody, MageBody, LoaderBody, CrocoBody, RailgunnerBody, RocketSurvivorBody, CHEF, SniperClassicBody, MinerBody, HANDOverclockedBody, RobPaladinBody, SS2UChirrBody, SS2UCyborgBody, SS2UExecutionerBody, SS2UPyroBody, SS2UNemmandoBody, RobDriverBody, DeputyBody

I assume is by adding "HuntressBody"?

**Comment by Moffein** [comment]
Yeah, that's correct.
For a full list of available bodies, install [DebugToolkit](https://thunderstore.io/package/IHarbHD/DebugToolkit/) and type body_list in console (Ctrl + Alt + ~).
This list will include both enemies and survivors.

**Comment by KaitoXion** [comment]
Thank you very much for your kind response.

What does this section actually does in the config file?
Based on my understanding, it's probably referring to *"spawn all character I have or added into the game"*; or does it does it spawn other characterBody that I haven't yet added into the game? (￣▽￣;)

> ## Allow all survivors to spawn, even if not listed in the Spawnlist.
> ## Setting type: Boolean
> ## Default value: false
> # All Survivors = false

If my understanding is correct, Then the Main Original Post of the config file code is for pointing out which specific character body is allowed to spawn.

If I am not wrong, the debugtoolkit is the one that pop-up when I attempt to lunch the game.
I'll test out the command as well.
Thank you so much for your guide. It really helps. + Your mod is super fun. ~ (･∀･)/　ﾊｰｲ

**Comment by Moffein** [comment]
All Survivors = false: Only survivors listed in the config will spawn.
All Survivors = true: All survivors in the in-game character select screen will spawn.

The pop-up window when booting up the game is something else.
DebugToolkit commands are run via the in-game console, which requires the previously mentioned key combination (Ctrl + Alt + ~ or ` depending on your keyboard) to open.

Glad to hear you're having fun with the mod!

**Comment by KaitoXion** [comment]
Fully noted on your kind reply.
My doubt or questions just saw the light of the day.

Thank you very much ~ ''`ｨ(´∀｀∩

> All Survivors = false: Only survivors listed in the config will spawn. All Survivors = true: All survivors in the in-game character select screen will spawn.
> 
> The pop-up window when booting up the game is something else. DebugToolkit commands are run via the in-game console, which requires the previously mentioned key combination (Ctrl + Alt + ~ or ` depending on your keyboard) to open.
