### ISSUE TITLE
Voidling's second phase does not spawn while the Artifact of Universe is active while used in conjunction with HIFU's Optimization mod

### ISSUE THREAD

**Issue by Aaron00000** [Moffein/Risky_Artifacts#24]
[LogOutput.log](https://github.com/Moffein/Risky_Artifacts/files/13954848/LogOutput.log)

Tested with RiskyArtifacts, [Optimization](https://thunderstore.io/package/HIFU/Optimization/), [AeroLt](https://thunderstore.io/package/Lodington/Aerolt/) (to quickly get to and kill Voidling), and their requirements.

**Comment by Moffein** [comment]
Judging by the log, I believe the issue is on Optimization's end.

**Comment by Aaron00000** [comment]
I'll take it up with HIFU then.
