### ISSUE TITLE
Hunted Survivors do Not Drop items when using artifact of sacrifice + Suggestion

### ISSUE THREAD

**Issue by iiVinii** [Moffein/Risky_Artifacts#25]
I'm playing with survivors spawning as normal enemies (and only survivors spawning), and i noticed that when using artifact of sacrifice they dont drop any item on Death

Also a suggestion is to Spawn the Survivor with Random Skills, and a Random Skin (if the Overlay is disabled)

**Comment by Moffein** [comment]
Thanks for reporting this, fixed it on my end. I'll be uploading an update soon.
Noting the suggestion, but I probably won't be able to get around to it as of now.
