### ISSUE TITLE
an artifact similar to Hunted

### ISSUE THREAD

**Issue by Phreelosu** [Moffein/Risky_Artifacts#26]
Honestly, I love this mod so much so thanks for developing this

I wish devs gave more love to void fields (as much as it sucks for some people), and maybe the idea is way too niche but an artifact that lets any characterbody (based on config) spawn as possible enemies in vields would be cool

if the answer is no I can understand why, but thanks for considering in advance!

**Comment by Moffein** [comment]
I don't play Void Fields enough to be motivated into making an artifact specific for it, but I'd be a-ok with lending out the code for Universe/Hunted if there's anyone else out there that wants to do something like that. I think making them Void Fields-specific would be simply a matter of changing the hook to check the current scenedef as well.

**Comment by Phreelosu** [comment]
oh alright!
I might do it myself then, thank you for the permission
