### ISSUE TITLE
Breakes artifact of honor

### ISSUE THREAD

**Issue by gammeflamme** [Moffein/Risky_Artifacts#3]
Using version 1.4.1 of this mod with game version 1.2.1.0 breaks artifact of honor so no elites spawn at all.

**Comment by Moffein** [comment]
Seems to be an issue on R2API's end, once that updates it should be fixed.

**Comment by MeatMorning** [comment]
It's not just honor, it breaks all elite spawns. I've spend 2 hours figuring it out

**Comment by Moffein** [comment]
R2API's EliteAPI is currently broken, so any mod that uses it will end up breaking elites. This mod uses EliteAPI for Origin's boss spawning code. R2API will have to fix the issue on their end.
