### ISSUE TITLE
[Bosses Drop Items][Minor Bug] Every Segment Of A Worm Boss Drops An Item

### ISSUE THREAD

**Issue by VaelophisNyx** [Moffein/Risky_Artifacts#4]
as the title suggests, in that particular mod, ever single segment of magma/overloading worms drops an item. Not game breaking, but a significant power boost to any run

**Comment by Moffein** [comment]
Thanks for reporting this, I'll take a look at it.

**Comment by VaelophisNyx** [comment]
You're welcome. Apologies about reporting it *here*, but I couldn't find a repo for that particular mod

**Comment by Moffein** [comment]
Just tested, Magma Worms are dropping 1 item as normal. Overloading Worms drop 5 items because they have 5x the credit cost of normal. I'll push an update and make this a config option.

**Comment by VaelophisNyx** [comment]
Thanks!
