### ISSUE TITLE
Expansion teleporter radius does not work

### ISSUE THREAD

**Issue by VarnaScelestus** [Moffein/Risky_Artifacts#5]
Title. The teleporter radius never expands past vanilla.

**Comment by Moffein** [comment]
Do you have ZetTweaks installed? Expansion is currently bugged when ZetTweaks' tele radius changes are enabled, but I plan to fix this sometime.

**Comment by VarnaScelestus** [comment]
That must be it. I definitely did have ZetTweaks installed.

**Comment by Moffein** [comment]
Fixed it.
